version: "3.9"

services:
  api:
    container_name: FastAPI_auth_test
    build: ./src
    command: uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8008
    ports:
      - "8000:8008"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    container_name: posgres_db_auth
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redisdb:
    container_name: redis_auth
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  postgres_db:
  redisdata:
    
